version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 895128774973.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - python -m unittest discover tests
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t pruebas-orquestador:latest ./pruebas-orquestador
      - docker tag pruebas-orquestador:latest 895128774973.dkr.ecr.us-east-1.amazonaws.com/pruebas-orquestador:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 895128774973.dkr.ecr.us-east-1.amazonaws.com/pruebas-orquestador:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"container-pruebas-orquestador","imageUri":"895128774973.dkr.ecr.us-east-1.amazonaws.com/pruebas-orquestador:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"895128774973.dkr.ecr.us-east-1.amazonaws.com/pruebas-orquestador:latest"}' > imageDetail.json
      - cat imagedefinitions.json
artifacts:
  files:
    - "**/*"
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
