version: '3.8'

services:
  jobs-cache:
    #image: "redis:alpine"
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    container_name: "jobs-redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      -  jobs-net

  jobs-db:
    image: postgres:13-alpine
    container_name: "jobs-pg"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=usrabc
      - POSTGRES_PASSWORD=pwdjobs
      - POSTGRES_DB=abcjobs
    networks:
      -  jobs-net

  candidatos-query:
    build: ./candidatos_qry
    image: candidatos-query:latest
    container_name: "candidatos-query-ms"
    ports:
      - 3691:80
    environment:
      - USERS_PATH=users
      - DB_USER=usrabc
      - DB_PASSWORD=pwdjobs
      - DB_HOST=jobs-db
      - DB_PORT=5432
      - DB_NAME=abcjobs
      # user_name: mango
      # write_result: show
    networks:
      -  jobs-net
    depends_on:
      - jobs-db

  pruebas-query:
    build: ./pruebas_qry  
    image: pruebas-query:latest
    container_name: "pruebas-query-ms"
    ports:
      - 3692:80
    environment:
      - USERS_PATH=users
      - DB_USER=usrabc
      - DB_PASSWORD=pwdjobs
      - DB_HOST=jobs-db
      - DB_PORT=5432
      - DB_NAME=abcjobs
    networks:
      -  jobs-net
    depends_on:
      - jobs-db

  pruebas-taker:
    build: .
    image: pruebas-taker:latest
    container_name: "pruebas-taker-ms"
    ports:
      - 3693:80
    environment:
      - USERS_PATH=users
      - ELASTICACHE_HOST = jobs-cache
      - ELASTICACHE_PORT= 6379
      - CANDIDATOS_QUERY_PATH = candidatos-query
      - PRUEBAS_QUERY_PATH = pruebas-query
      - CANDIDATOS_QUERY_PORT = 3691
      - PRUEBAS_QUERY_PORT = 3692
    networks:
      -  jobs-net
    depends_on:
      - jobs-cache

volumes:
  postgres_data:

networks:
  jobs-net:
    driver: bridge
