# Ejemplo de github action para probar python
# Docs: https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions
#name: Example CI
name: Grupo 18 CI DEV

on:
  push:
    branches:
      - develop
jobs:
  test-posts-saga:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v1
      - name: Install environment
        working-directory: ./companies
        run: |
          pip install pipenv
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
      - name: Run unit tests
        working-directory: ./companies
        run: |
          pytest --cov=. -v -s --cov-fail-under=80
