# Ejemplo de github action para probar python
# Docs: https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions
name: Grupo-18 CI/CD Dev

on:
  push:
    branches:
      - develop
  pull_request:
    branches: 
      - develop

# check for run job based on file changes in GitHub Actions
# https://how.wtf/run-workflow-step-or-job-based-on-file-changes-github-actions.html
jobs:
  pruebas-cmd:
    uses: ./.github/workflows/test-build-deploy.yml
    with:
       microservice: pruebas-cmd
       microservice-path: ./pruebas_cmd
    secrets: inherit

  pruebas-qry:
    uses: ./.github/workflows/test-build-deploy.yml
    with:
       microservice: pruebas-qry
       microservice-path: ./pruebas_qry
    secrets: inherit

